const verbHelpers = [
  ["ます", "do~, will~ (formal)", 1],
  ["ました", "did~ (formal)", 1],
  ["ません", "don't~, won't~ (formal)", 1],
  ["ませんでした", "didn't~ (formal", 1],
  ["る", "do~, will~ (informal)", ""],
  ["た", "~did (informal", ""],
  ["ない", "~don't, won't~ (informal)", ""],
  ["なかった", "~didn't (informal)", ""],
  ["(ら)れる", "able to~, can~", ""],
  ["(ら)れた", "was able to~, could~", ""],
  ["(ら)れない", "won't be able to~, can't~", ""],
  ["(ら)れなかった", "wasn't able to~, couldn't~", ""],
  ["られる", "to be~ (+3 rd form)", ""],
  ["られた", "was~ (+3 rd form)", ""],
  ["られない", "to not be~ (+ 3rd form)", ""],
  ["られなかった", "wasn't (+ 3rd form)", ""],
  ["される", "", ""],
  ["された", "", ""],
  ["されない", "", ""],
  ["されなかった", "", ""],
  ["たい", "want to~", ""],
  ["たかった", "wanted to~", ""],
  ["たくない", "don't want to~", ""],
  ["たくなかった", "didn't want to~", ""],
  ["ましょう", "let's~ (formal)", ""],
  ["う", "let's~ (formal)", ""],
  ["よう", "let's~ (informal)", ""],
  ["こと", "to~, ~ing (noun)", ""],
  ["て", "do~ (command)", ""],
  ["ないで", "don't~ (command)", ""],
  ["ないほうがいい", "shouldn't do~", ""],
  ["なくてもいい", "don't have to~", ""],
];
